[versions]
kotlin = "1.7.20"
java = "17"
# TODO Update AGP to 7.4 or higher, to fix, https://issuetracker.google.com/issues/194113162
android = "7.3.1" #-- Android Gradle Plugin (AGP)
compose-mpp = "1.2.1"
